[package]
name = "edit-config"
version = "0.1.0"
authors = ["Arseniy Kucher <orsen.kucher@gmail.com>"]
edition = "2018"

[dependencies]
toml_edit = { git = "https://github.com/orsenkucher/toml_edit" }
