[package]
name = "learn-wgpu"
version = "0.1.0"
authors = ["Arseniy Kucher <orsen.kucher@gmail.com>"]
edition = "2018"

[dependencies]
image = "0.23"
winit = "0.22"
shaderc = "0.6"
cgmath = "0.17"
env_logger = "0.7"
log = "0.4"
wgpu = "0.6"
futures = "0.3"
