[package]
name = "read-config"
version = "0.1.0"
authors = ["Arseniy Kucher <orsen.kucher@gmail.com>"]
edition = "2018"

[dependencies]
serde = { version = "1.0.116", features = ["derive"] }
toml = "0.5.6"
